import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import EnvelopedLogin from "@/components/enveloped-login-btn";
import { IoIosLogOut } from "react-icons/io";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Contact Book",
  description: "Generated by create next app",
};

const islogin = false



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Header componentProps={islogin ? <EnvelopedLogin /> : <Link className="flex items-center" href="#">
          <h2 className="text-white">Sair</h2>
          <IoIosLogOut size={40} color="#ffffff" className="mx-5" />
        </Link>} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
